dependencies:
  - python==3.11
  - pip
  - pip:
      - matplotlib
      - astropy
      - pandas
      - requests
      - loguru
      - git+https://github.com/tedjohnson12/libpypsg.git@main
      - GridPolator
      - git+https://github.com/VSPEC-Collab/VSPEC.git@release/1.2.0
      - asdf
      - asdf-astropy==0.8.0
      - colorlog
      - git+https://github.com/tedjohnson12/vpie-rs.git
