dependencies:
  - python==3.11
  - pip
  - pip:
      - matplotlib
      - astropy
      - pandas
      - requests
      - libpypsg
      - GridPolator
      - git+https://github.com/tedjohnson12/vpie-rs.git
